apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orchestrator
spec:
  selector:
    app: {{ .Release.Name }}-orchestrator
  ports:
    - port: {{ .Values.orchestrator.port }}
      targetPort: {{ .Values.orchestrator.port }}
